version: '3.8'
services:
  # You need to build the fluentd docker image
  # to install the elasticsearch gem plugin
  fluentd:
    image: fluentd-with-s3
    build: ./fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    volumes:
      - ./fluentd:/fluentd/etc
    environment:
      AWS_KEY_ID: "${KEY}"
      AWS_SECRET_KEY: "${SECRET_KEY}"
      S3_BUCKET: "${S3_BUCKET}"
      S3_REGION: "${S3_REGION}"
    networks:
      - net

  nginx:
    image: nginx:1.19.2
    volumes:
      - ./nginx/index.html:/usr/share/nginx/html/index.html
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 4000:80
    logging:
      driver: fluentd
      options:
        tag: docker.nginx
    networks:
      - net
    depends_on:
      - fluentd
networks:
      net:
          driver: bridge
